# Generated by Django 6.0.7 on 2026-07-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date_heure']},
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='duree',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='lieu',
            field=models.CharField(default='Cabinet', max_length=255),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('planifié', 'Planifié'), ('confirmé', 'Confirmé'), ('reporté', 'Reporté'), ('en_cours', 'En cours'), ('terminé', 'Terminé'), ('annulé', 'Annulé')], default='planifié', max_length=20),
        ),
    ]
